version: "3.7"
services:

    service-mysql:
        volumes:
            - service-mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"
            
    chat-api:
        ports:
            - "9235:9229"
        build:
            context: ./chat_api
            dockerfile: Dockerfile
        volumes:
            - ./chat_api/code:/app

volumes:
    service-mysql-volume:
        driver: local
