version: "3.7"
services:
    # API em Node JS
    chat-api:
        image: rafaellessa/chat-api:${DOCKER_IMAGE_TAG:-latest}
        volumes:
            - /app/node_modules/
        ports:
            - "${CHAT_API_PORT:-3000}:${CHAT_API_PORT:-3001}"
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "10m"
        environment:

            #Mysql
            MYSQL_DB_HOST: service-mysql
            MYSQL_DB_PORT: 3306
            MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
            MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
            MYSQL_DB_DATABASE: ${MYSQL_DB_DATABASE}

            # Redis
            REDIS_HOST: service-redis
            REDIS_PORT: 6379
            REDIS_CACHE_DB: 0
            REDIS_DB: 0
            REDIS_PREFIX: "CacheChat:"
            CACHE_PREFIX: "Chat:"

            # Ambiente do node
            CHAT_API_ENV: ${CHAT_API_ENV}
            CHAT_API_PORT: ${CHAT_API_PORT}

            JWT_SECRET: ${JWT_SECRET}

        networks:
            - service-network

        restart: unless-stopped

networks:
    service-network:
        external: true
